/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./../views/css/css-effect/components/A.vue')['default']
    B: typeof import('./../views/css/css-effect/components/B.vue')['default']
    C: typeof import('./../views/css/css-effect/components/C.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FourDivision: typeof import('./../views/css/css-effect/components/FourDivision.vue')['default']
    Header: typeof import('./../views/layout/components/SideNav/src/Header.vue')['default']
    HeaderTabs: typeof import('./../views/layout/components/HeaderTabs.vue')['default']
    HoverCard: typeof import('./../views/css/css-effect/components/HoverCard.vue')['default']
    PageSelect: typeof import('./../views/ele-plus/components/PageSelect.vue')['default']
    RadioGroup: typeof import('./../views/ele-plus/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./../views/layout/components/SideNav/index.ts')['default']
    SideNavItem: typeof import('./../views/layout/components/SideNav/src/SideNavItem.vue')['default']
    TerminalDate: typeof import('./../views/ts/ts-effect/components/TerminalDate.vue')['default']
    UserInfoCard: typeof import('./../views/layout/components/UserInfoCard.vue')['default']
  }
}
